server:
  port: 8090
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
      
spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: info-service
          uri: lb://INFO-SERVICE
          predicates:
          - Path=/member/**
        - id: auth-service
          uri: lb://auth-SERVICE
          predicates:
          - Path=/**
      